### PR TITLE
Fix for scaling, robot size and robot speed. Fixes #54

### LINKED ISSUE #54: Changing the map scaling causes exception
When the map scaling factor in MapConfig is changed to a value that is not one (ie. 2 or 3) several exception are throw when the play button is pressed.

### PR DESCRIPTION
**Pull request by philipholler**
Fixes issuse #54

### CODE REVIEW

File: Assets/Scripts/Robot/MovementDirective.cs [hunk 1]
```diff
@@ -5,17 +5,31 @@ namespace Maes.Robot {
...
+        public static MovementDirective NoMovement() {
+            return new MovementDirective(0f, 0f);
+        }
 
         public MovementDirective(float leftWheelSpeed, float rightWheelSpeed) {
-            if (leftWheelSpeed > 1.0f || leftWheelSpeed < -1.0f || rightWheelSpeed > 1.0f || rightWheelSpeed < -1.0f)
+            /*if (leftWheelSpeed > 1.0f || leftWheelSpeed < -1.0f || rightWheelSpeed > 1.0f || rightWheelSpeed < -1.0f)
                 throw new ArgumentException($"Left and right wheel speeds must be within bounds [-1.0, 1.0]" +
-                                            $" but given left/right speeds were {leftWheelSpeed} and {rightWheelSpeed}");
+                                            $" but given left/right speeds were {leftWheelSpeed} and {rightWheelSpeed}");*/
```
Comment (MalteZA) [inline Assets/Scripts/Robot/MovementDirective.cs:32]: Maybe just delete?

**Review by MalteZA — APPROVED** [review]
